RUN:
  bin_dir: './bin'
  client_version: '4.16.0-rc.9'
DEPLOYMENT:
  force_download_installer: false
  installer_version : "4.16.0-rc.9"
  ssh_key: "~/.ssh/id_ed25519.pub"
  # ocp_mirror_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp-dev-preview"
ENV_DATA:
  region: 'us-east-1'
  master_instance_type: 'm5.xlarge'
  worker_instance_type: 'm5.2xlarge'
  service_network_cidr: "172.31.0.0/16"
  cluster_network_cidr: "10.132.0.0/14"
  skip_ocp_deployment: true
  skip_ocs_deployment: true
  skip_ocs_cluster_creation: true
  enable_ocs_plugin: false
  ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.16.0"
  ocs_csv_channel: "stable-4.16"
  ocs_version: '4.16'
MULTICLUSTER:
  acm_cluster: true
  primary_cluster: true
  configure_submariner: true
  skip_mco_deployment: true
  enable_mco_plugin: false
  deploy_acm_hub_cluster: false
  import_managed_clusters: false
  exchange_ssl_certificate: false
  # comment this out for acm unreleased version
  # acm_hub_channel: 'release-2.10'
  # enable this for ACM un-released build
  acm_hub_unreleased: false
  acm_unreleased_image: "2.11.0-DOWNSTREAM-2024-06-08-19-26-47"
  skip_gitops_deployment: true
REPORTING:
  email:
    skip_notification: true
  messenger:
    skip_notification: true
