apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: redhat-oadp-operator-unreleased-catalog
spec:
  imageDigestMirrors:
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-cli-binaries-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-hypershift-velero-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-kubevirt-datamover-controller-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-kubevirt-datamover-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-kubevirt-velero-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-mustgather-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-non-admin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-operator-bundle
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-rhel9-operator
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-plugin-for-aws-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-plugin-for-gcp-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-plugin-for-legacy-aws-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-plugin-for-microsoft-azure-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-plugin-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-velero-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-vm-file-restore-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-vmdp-binaries-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-vmfr-access-filebrowser-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-vmfr-access-rhel9
  - mirrors:
    - quay.io/redhat-user-workloads/ocp-art-tenant/art-images-share
    source: registry.redhat.io/oadp/oadp-vmfr-access-sshd-rhel9
