ENV_DATA:
  skip_ocp_deployment: true
MULTICLUSTER:
  acm_cluster: true
  primary_cluster: true
  deploy_acm_hub_cluster: true
  import_managed_clusters: true
  acm_hub_unreleased: true
  acm_unreleased_image: "v2.10.1-FC0"
REPORTING:
  email:
    skip_notification: true
