apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-applicationset-controller-placement
  namespace: openshift-gitops
rules:
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules
  verbs:
  - list
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placementdecisions
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-applicationset-controller-placement
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-applicationset-controller-placement
subjects:
- kind: ServiceAccount
  name: openshift-gitops-applicationset-controller
  namespace: openshift-gitops
