RUN:
  client_version: '4.19.0-0.nightly'
DEPLOYMENT:
  force_download_installer: false
  installer_version : "4.19.0-0.nightly"
  ssh_key: "~/.ssh/id_rsa.pub"
  # ocp_mirror_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp"
ENV_DATA:
  master_instance_type: 'm4.xlarge'
  worker_instance_type: 'm4.2xlarge'
  worker_replicas: 3
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  skip_ocs_cluster_creation: true
  enable_ocs_plugin: true
  ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.19.0"
  # ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-konflux-upgrade-4.19.0"
  ocs_csv_channel: "stable-4.19"
  ocs_version: '4.19'
REPORTING:
  email:
    skip_notification: false
  messenger:
    skip_notification: false

