RUN:
  bin_dir: './bin/nooba'
  client_version: '4.10.0'
DEPLOYMENT:
  force_download_installer: true
  installer_version : "4.10.0"
  ssh_key: "~/.ssh/id_rsa.pub"
  ocp_mirror_url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp"
ENV_DATA:
  master_instance_type: 'm5.xlarge'
  worker_instance_type: 'm5.2xlarge'
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  skip_ocs_cluster_creation: true
  enable_ocs_plugin: true
  ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.10.0"
  ocs_csv_channel: "stable-4.10"
  ocs_version: '4.10'
REPORTING:
  email:
    skip_notification: false
  messenger:
    skip_notification: false

